CREATE TABLE PERSON (PID NUMBER,NAME VARCHAR,SALARY DOUBLE);
SELECT * FROM PERSON;
INSERT INTO PERSON VALUES(2,'Neeraj',100.05);
UPDATE PERSON SET SALARY = 200.06 WHERE PID=2 ;
DROP TABLE TEST_EMPLOYEE;
INSERT INTO PERSON VALUES(" + id + ", '" + name + "'," + sal + "); 